import { StyleSheet, Dimensions } from 'react-native';

const styles = StyleSheet.create({
  image: {
    width: '100%',
    minHeight: 400,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'skyblue',
    paddingVertical: 24,
  },
  loanTitleView: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    marginBottom: 18,
    width: '92%',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#e29d58',
    textAlign: 'center',
  },
  sendLoanView: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
    width: '92%',
    alignItems: 'flex-start',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  sendLoanText: {
    fontSize: 15,
    color: '#1a237e',
    marginTop: 6,
    marginLeft: 2,
  },
  sendLoanInput: {
    backgroundColor: '#f0f4ff',
    borderRadius: 8,
    height: 48,
    paddingHorizontal: 14,
    fontSize: 16,
    color: '#222',
    borderWidth: 1,
    borderColor: '#e29d58',
    width: '100%',
  },
  sendLoanButton: {
    backgroundColor: '#e29d58',
    borderRadius: 24,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 8,
    width: '92%',
    alignSelf: 'center',
    shadowColor: '#e29d58',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 2,
  },
  sendLoanButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 17,
  },
});

export default styles;
